#!/usr/bin/env python3

import sys
sys.path.append("/usr/lib/python3/dist-packages")

if 1:
    import mittenwire
    import rospy

rospy.init_node("mittenwire", disable_signals=True)


class App(mittenwire.App):

    def __init__(self):
        super().__init__("View")
        self.tactile_timestamp = 0
        self.w = 0
        self.h = 0

    def process_tactile_matrix(self, msg):
        self.pub_mat.publish(msg)
        self.tactile_timestamp = msg.timestamp

    def process_camera_image(self, msg):
        super().process_camera_image(msg)
        self.w = msg.width
        self.h = msg.height
        # print("image", msg.channel, msg.request_timestamp,
        #       msg.width, msg.height, msg.skip)

    def render(self, width, height):
        # text = "mode: viewer    timestamp: %i    frametime: %.2f    fps: %4.2f" % (
        #     self.frame_timestamp, self.frame_time, self.frames_per_second)
        text = "mode viewer    itime %i    ttime %i    diff %i    fps %.3f    res %i x %i" % (
            self.frame_timestamp, self.tactile_timestamp, self.tactile_timestamp - self.frame_timestamp, self.frames_per_second, self.w, self.h)
        return super().render(width, height, text)


app = App()
app.run()

rospy.signal_shutdown("")

print("exit")
