#!/usr/bin/env python3

import sys
import rospkg
import pyassimp
import lxml.etree as et
import tf.transformations
import numpy as np
import rospy
import glovewise


glove = glovewise.GloveModel()
glove.load_resource("glovewise", "/models/" + sys.argv[1] + ".dae")


urdf = glove.build_urdf()
print(urdf)
rospy.set_param("robot_description", urdf)
